#文件保存路径
download_path="/home/yang/Videos/"

#个人主页链接
#url="https://www.douyin.com/user/MS4wLjABAAAAXtFyj0PMW0KNUioPnvedRBnq502o6VpO51pfFRWeWm_QECYgE8CrsVtx2oH455l-"
url="https://v.douyin.com/YFnAFye/"
#是否下载超高清视频1080P，否则720P
isUHD = true

[grpc]
addr="127.0.0.1"
port="9090"